version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./docker_data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME:-TransIT}
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
  web:
    build: .
    command: start
    volumes:
      - ./:/backend
      - ${PWD}/tox.ini:/backend/tox.ini
      - ${PWD}/server.py:/backend/server.py
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=${DB_NAME:-TransIT}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - DB_HOST=${DB_HOST:-db} # By default, it's pointing to db container
      - DB_PORT=${DB_PORT:-5432}
      - PORT=${PORT:-8000}
      - DJANGO_SERVER=${DJANGO_SERVER:-django_wsgi} # By default, use development server, actual server should use 'waitress'
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*} # Warning: '*' should not be used in production
      - SUPERUSER_LOGIN=${SUPERUSER_LOGIN}
      - SUPERUSER_PASSWORD=${SUPERUSER_PASSWORD}
      - SUPERUSER_EMAIL=${SUPERUSER_EMAIL}
    depends_on:
      db:
        condition: service_started
