# Generated by Django 4.0.6 on 2022-08-15 19:08

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('transit', '0002_usermanager_squashed_0004_alter_usermanager_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormsClerk',
            fields=[
            ],
            options={
                'permissions': [('can_manage_forms', 'Can manage forms')],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
