# Generated by Django 4.0.6 on 2022-08-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0003_formsclerk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='composite_product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='itemdetails',
            old_name='item_product',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='transporter',
            old_name='transporter_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(db_column='Name', default='UNDEFINED', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customertype',
            name='customer_type_name',
            field=models.CharField(blank=True, db_column='CustomerTypeName', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='conditions',
            field=models.CharField(choices=[('', ''), ('ColdChain', 'Cold Chain'), ('Ambient', 'Ambient')], db_column='Conditions', default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='batch_number',
            field=models.CharField(db_column='BatchNumber', default='UNDEFINED', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderlinedetails',
            name='old_quantity',
            field=models.DecimalField(db_column='OldQuantity', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='orderlinedetails',
            name='quantity',
            field=models.DecimalField(db_column='Quantity', decimal_places=2, default=0, max_digits=18),
            preserve_default=False,
        ),
    ]
