# Generated by Django 4.0.6 on 2022-08-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0004_rename_customer_name_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetails',
            name='item',
            field=models.ForeignKey(db_column='ItemID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_details', to='transit.item'),
        ),
    ]
