# Generated by Django 4.0.6 on 2022-08-29 10:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import transit.models.shipment


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0004_rename_customer_name_customer_name_and_more_squashed_0009_alter_orderlinedetails_order_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 43, 27, 572066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customertype',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 43, 27, 572066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 43, 27, 572066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 43, 27, 572066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 43, 27, 572066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='modeoftransport',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 43, 27, 572066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 43, 27, 572066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderlinedetails',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 43, 27, 572066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderlinedetails',
            name='order_details',
            field=models.ForeignKey(db_column='OrderDetailsID', on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='transit.orderdetails'),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 43, 27, 572066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='podvariance',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 43, 27, 572066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='podvariancedetails',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 43, 27, 572066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='podvariancedetails',
            name='pod_variance',
            field=models.ForeignKey(db_column='PODVarianceID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='details', to='transit.podvariance'),
        ),
        migrations.AlterField(
            model_name='portalaccess',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 43, 27, 572066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentdetails',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 43, 27, 572066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentordermapping',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 43, 27, 572066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 43, 27, 572066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 43, 27, 572066, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transporterdetails',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 43, 27, 572066, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='ShipmentDetailFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=transit.models.shipment.content_file_name)),
                ('shipment', models.ForeignKey(db_column='ShipmentDetailsID', on_delete=django.db.models.deletion.CASCADE, to='transit.shipmentdetails')),
            ],
        ),
    ]
