# Generated by Django 4.0.6 on 2022-08-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0005_alter_itemdetails_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driver',
            old_name='driver_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='shipmentdetails',
            name='delivery_date',
            field=models.DateTimeField(db_column='DeliveryDate', null=True),
        ),
        migrations.AlterField(
            model_name='shipmentdetails',
            name='expected_delivery_date',
            field=models.DateTimeField(db_column='ExpectedDeliveryDate', null=True),
        ),
        migrations.AlterField(
            model_name='shipmentdetails',
            name='number_of_kilometers',
            field=models.DecimalField(db_column='NumberOfKilometers', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentdetails',
            name='pod',
            field=models.BooleanField(db_column='POD', null=True),
        ),
        migrations.AlterField(
            model_name='shipmentdetails',
            name='ship_date',
            field=models.DateTimeField(db_column='ShipDate', null=True),
        ),
        migrations.AlterField(
            model_name='shipmentdetails',
            name='timestamp',
            field=models.DateTimeField(db_column='Timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='shipmentdetails',
            name='transporter_additional_cost',
            field=models.DecimalField(db_column='TransporterAdditionalCost', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentdetails',
            name='transporter_base_cost',
            field=models.DecimalField(db_column='TransporterBaseCost', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='shipmentdetails',
            name='transporter_per_diem',
            field=models.DecimalField(db_column='TransporterPerDiem', decimal_places=2, max_digits=18, null=True),
        ),
    ]
