# Generated by Django 4.0.6 on 2022-08-29 10:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0005_alter_customer_last_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentdetailfiles',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 55, 17, 616362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='customertype',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 55, 17, 616362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='driver',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 55, 17, 616362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='item',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 55, 17, 616362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 55, 17, 616362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='modeoftransport',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 55, 17, 616362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 55, 17, 616362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderlinedetails',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 55, 17, 616362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 55, 17, 616362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='podvariance',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 55, 17, 616362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='podvariancedetails',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 55, 17, 616362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='portalaccess',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 55, 17, 616362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentdetails',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 55, 17, 616362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shipmentordermapping',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 55, 17, 616362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 55, 17, 616362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transporter',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 55, 17, 616362, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transporterdetails',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=datetime.datetime(2022, 8, 29, 10, 55, 17, 616362, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='shipmentdetailfiles',
            table='ShipmentDetailFiles',
        ),
    ]
