# Generated by Django 4.0.6 on 2022-08-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0006_rename_driver_name_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystatus',
            name='delivery_status_key',
            field=models.CharField(db_column='DeliveryStatusKey', max_length=64, primary_key=True, serialize=False, unique=True, blank=False, null=False),
        ),
    ]
