# Generated by Django 4.0.6 on 2022-08-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0007_alter_deliverystatus_delivery_status_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='order_details_id',
            field=models.CharField(db_column='OrderDetailsID', max_length=64, primary_key=True, serialize=False, unique=True, blank=False, null=False),
        ),
    ]
