# Generated by Django 4.0.6 on 2022-08-19 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0008_alter_orderdetails_order_details_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlinedetails',
            name='order_details',
            field=models.ForeignKey(db_column='OrderDetailsID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='line_items', to='transit.orderdetails'),
        ),
    ]
