# Generated by Django 4.0.6 on 2022-09-08 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transit', '0008_historicaltransporterdetails_historicaltransporter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerweekdays',
            name='last_modified_by',
            field=models.CharField(db_column='LastModifiedBy', default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerweekdays',
            name='last_modified_date',
            field=models.DateTimeField(db_column='LastModifiedDate', default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='HistoricalCustomerWeekDays',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('last_modified_date', models.DateTimeField(db_column='LastModifiedDate', default=django.utils.timezone.now)),
                ('last_modified_by', models.CharField(db_column='LastModifiedBy', max_length=255)),
                ('day', models.IntegerField(db_column='Day')),
                ('opening_time', models.CharField(db_column='OpeningTime', max_length=50)),
                ('closing_time', models.CharField(db_column='ClosingTime', max_length=50)),
                ('closed', models.BooleanField(blank=True, db_column='Closed', default=False, null=True)),
                ('meridiem_indicator_opening_time', models.CharField(blank=True, db_column='Meridiem_Indicator_OpeningTime', max_length=20, null=True)),
                ('meridiem_indicator_closing_time', models.CharField(blank=True, db_column='Meridiem_Indicator_ClosingTime', max_length=20, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('customer', models.ForeignKey(blank=True, db_column='CustomerID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='transit.customer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical customer week days',
                'verbose_name_plural': 'historical customer week dayss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
