# Generated by Django 4.0.6 on 2022-09-26 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0009_customerweekdays_last_modified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(db_column='Email', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(db_column='FirstName', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(db_column='LastName', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(db_column='Phone', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customertype',
            name='customer_type_name',
            field=models.CharField(db_column='CustomerTypeName', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customerweekdays',
            name='closed',
            field=models.BooleanField(db_column='Closed', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customerweekdays',
            name='closing_time',
            field=models.CharField(db_column='ClosingTime', default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='customerweekdays',
            name='customer',
            field=models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, related_name='week_days', to='transit.customer'),
        ),
        migrations.AlterField(
            model_name='customerweekdays',
            name='opening_time',
            field=models.CharField(db_column='OpeningTime', default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='email',
            field=models.CharField(db_column='Email', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='first_name',
            field=models.CharField(db_column='FirstName', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='last_name',
            field=models.CharField(db_column='LastName', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='phone',
            field=models.CharField(db_column='Phone', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomertype',
            name='customer_type_name',
            field=models.CharField(db_column='CustomerTypeName', db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomerweekdays',
            name='closed',
            field=models.BooleanField(db_column='Closed', default=False, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomerweekdays',
            name='closing_time',
            field=models.CharField(db_column='ClosingTime', default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalcustomerweekdays',
            name='opening_time',
            field=models.CharField(db_column='OpeningTime', default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='cost',
            field=models.DecimalField(db_column='Cost', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='volume',
            field=models.DecimalField(db_column='volume', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='historicalitemdetails',
            name='expiry_date',
            field=models.DateTimeField(db_column='ExpiryDate', null=True),
        ),
        migrations.AlterField(
            model_name='historicalitemdetails',
            name='manufacturing_date',
            field=models.DateTimeField(db_column='ManufacturingDate', null=True),
        ),
        migrations.AlterField(
            model_name='historicalitemdetails',
            name='received_date',
            field=models.DateTimeField(db_column='ReceivedDate', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.DecimalField(db_column='Cost', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='volume',
            field=models.DecimalField(db_column='volume', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='expiry_date',
            field=models.DateTimeField(db_column='ExpiryDate', null=True),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='manufacturing_date',
            field=models.DateTimeField(db_column='ManufacturingDate', null=True),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='received_date',
            field=models.DateTimeField(db_column='ReceivedDate', null=True),
        ),
        migrations.AlterField(
            model_name='shipmentordermapping',
            name='shipment_details',
            field=models.ForeignKey(db_column='ShipmentDetailsID', on_delete=django.db.models.deletion.CASCADE, related_name='order_mapping', to='transit.shipmentdetails'),
        ),
    ]
