# Generated by Django 4.0.6 on 2022-09-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0010_alter_customer_email_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(blank=True, db_column='Email', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(blank=True, db_column='FirstName', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, db_column='LastName', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, db_column='Phone', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customertype',
            name='customer_type_name',
            field=models.CharField(blank=True, db_column='CustomerTypeName', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='email',
            field=models.CharField(blank=True, db_column='Email', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='first_name',
            field=models.CharField(blank=True, db_column='FirstName', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='last_name',
            field=models.CharField(blank=True, db_column='LastName', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomer',
            name='phone',
            field=models.CharField(blank=True, db_column='Phone', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcustomertype',
            name='customer_type_name',
            field=models.CharField(blank=True, db_column='CustomerTypeName', db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='cost',
            field=models.DecimalField(blank=True, db_column='Cost', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='volume',
            field=models.DecimalField(blank=True, db_column='volume', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='historicalitemdetails',
            name='expiry_date',
            field=models.DateTimeField(blank=True, db_column='ExpiryDate', null=True),
        ),
        migrations.AlterField(
            model_name='historicalitemdetails',
            name='manufacturing_date',
            field=models.DateTimeField(blank=True, db_column='ManufacturingDate', null=True),
        ),
        migrations.AlterField(
            model_name='historicalitemdetails',
            name='received_date',
            field=models.DateTimeField(blank=True, db_column='ReceivedDate', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.DecimalField(blank=True, db_column='Cost', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='volume',
            field=models.DecimalField(blank=True, db_column='volume', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='expiry_date',
            field=models.DateTimeField(blank=True, db_column='ExpiryDate', null=True),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='manufacturing_date',
            field=models.DateTimeField(blank=True, db_column='ManufacturingDate', null=True),
        ),
        migrations.AlterField(
            model_name='itemdetails',
            name='received_date',
            field=models.DateTimeField(blank=True, db_column='ReceivedDate', null=True),
        ),
    ]
