# Generated by Django 4.0.6 on 2022-10-03 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0011_alter_customer_email_alter_customer_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorderdetails',
            name='order_details_id',
            field=models.CharField(db_column='OrderDetailsID', db_index=True, default='221003075826819565', max_length=64),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order_details_id',
            field=models.CharField(db_column='OrderDetailsID', default='221003075826819565', max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='podvariancedetails',
            name='pod_variance',
            field=models.ForeignKey(db_column='PODVarianceID', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='transit.podvariance'),
        ),
    ]
