# Generated by Django 4.0.6 on 2022-10-03 08:16

from django.db import migrations, models
import transit.models.order_details


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0012_alter_historicalorderdetails_order_details_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorderdetails',
            name='order_details_id',
            field=models.CharField(db_column='OrderDetailsID', db_index=True, default=transit.models.order_details.generate_order_id, max_length=64),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order_details_id',
            field=models.CharField(db_column='OrderDetailsID', default=transit.models.order_details.generate_order_id, max_length=64, primary_key=True, serialize=False, unique=True),
        ),
    ]
