# Generated by Django 4.0.6 on 2022-10-03 08:16

from django.db import migrations, models
import transit.models.order_details


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0012_alter_historicalorderdetails_order_details_id_and_more'),
    ]

    operations = [
    ]
