# Generated by Django 4.0.6 on 2022-10-02 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0014_alter_historicalitem_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='transporter',
            field=models.ForeignKey(db_column='TransporterID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='drivers', to='transit.transporter'),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='cost',
            field=models.DecimalField(blank=True, db_column='Cost', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='volume',
            field=models.DecimalField(blank=True, db_column='volume', decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='weight',
            field=models.DecimalField(blank=True, db_column='Weight', decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.DecimalField(blank=True, db_column='Cost', decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='volume',
            field=models.DecimalField(blank=True, db_column='volume', decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.DecimalField(blank=True, db_column='Weight', decimal_places=6, max_digits=18, null=True),
        ),
    ]
