# Generated by Django 4.0.6 on 2022-10-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0015_alter_driver_transporter_alter_historicalitem_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltransporterdetails',
            name='vehicle_capacity_volume',
            field=models.DecimalField(db_column='VehicleCapacityVolume', decimal_places=6, max_digits=18, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltransporterdetails',
            name='vehicle_capacity_weight',
            field=models.DecimalField(db_column='VehicleCapacityWeight', decimal_places=6, max_digits=18, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transporterdetails',
            name='vehicle_capacity_volume',
            field=models.DecimalField(db_column='VehicleCapacityVolume', decimal_places=6, max_digits=18, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='transporterdetails',
            name='vehicle_capacity_weight',
            field=models.DecimalField(db_column='VehicleCapacityWeight', decimal_places=6, max_digits=18, max_length=255, null=True),
        ),
    ]
