# Generated by Django 4.0.6 on 2022-10-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0016_alter_historicaltransporterdetails_vehicle_capacity_volume_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystatus',
            name='delivery_status',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('delivered', 'Delivered'), ('not_delivered', 'Not Delivered')], db_column='DeliveryStatus', default='undefined', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicalpodvariance',
            name='dso_type',
            field=models.CharField(choices=[('damaged', 'Damaged'), ('short', 'Short'), ('over', 'Over'), ('other', 'Other')], db_column='DSOType', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='podvariance',
            name='dso_type',
            field=models.CharField(choices=[('damaged', 'Damaged'), ('short', 'Short'), ('over', 'Over'), ('other', 'Other')], db_column='DSOType', max_length=255, null=True),
        ),
    ]
