# Generated by Django 4.0.6 on 2022-10-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0017_alter_deliverystatus_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverystatus',
            name='delivery_status',
            field=models.CharField(choices=[('undefined', 'Undefined'), ('delivered', 'Delivered'), ('not_delivered', 'Not Delivered'), ('other', 'Other'), ('pod_signed_complete', 'POD signed complete'), ('pod_signed_dso', 'POD signed DSO'), ('robbery', 'Robbery'), ('accident', 'Accident'), ('client_not_present', 'Client not present')], db_column='DeliveryStatus', default='undefined', max_length=50),
        ),
    ]
