CUSTOMER_EXAMPLE_DATA = [{
    'Customer ID': 'Private Clinic',
    'Name': 'CLIENTTest1',
    'First Name': 'John',
    'Last Name': 'Doe',
    'Address 1': 'Add1',
    'Address 2': 'Add2',
    'Address 3': 'Add3',
    'City': 'City1',
    'State': 'State1',
    'Country': 'Country1',
    'Phone': '9123912',
    'Email': 'email@email.email',
    'LatitudeLongitude': 'latlong',
}, {
    'Customer ID': 'Private Clinic',
    'Name': 'CLIENTTest2',
    'First Name': '',
    'Last Name': '',
    'Address 1': '',
    'Address 2': '',
    'Address 3': '',
    'City': '',
    'State': '',
    'Country': '',
    'Phone': '',
    'Email': '',
    'LatitudeLongitude': '',
}]


ITEM_DETAILS_EXAMPLE_DATA = [{
    'Item Code': 'ABA001-TAB001-30',
    'Name': 'Test Item 1',
    'Batch Number': 'BN001',
    'Expiry Date': '31/12/2023',
    'Date of Manufacture': '02/01/2021',
    'Date Received': '10/12/2022',
    'GTIN': '12345',
    'Lot Number': 'lotnumber',
    'Serial Number': '12367',
    'Funding Source': 'Test Source 1',
}, {
    'Item Code': 'ABA002-TAB001-30',
    'Name': 'Test Item 2',
    'Batch Number': 'BN002',
    'Expiry Date': '',
    'Date of Manufacture': '',
    'Date Received': '',
    'GTIN': '',
    'Lot Number': '',
    'Serial Number': '',
    'Funding Source': '',
}]


ITEM_MASTER_EXAMPLE_DATA = [{
    'Item Code': 'ABA001-TAB001-30',
    'Name': 'Test Item 1',
    'Category': 'CAT1',
    'Sub Category': 'SUBCAT1',
    'Volume': 10,
    'Weight': 11,
    'Cost': 21,
    'Is ColdChain': True,
}, {
    'Item Code': 'ABA002-TAB001-30',
    'Name': 'Test Item 2',
    'Category': 'cat2',
    'Sub Category': '',
    'Volume': '',
    'Weight': 4.5,
    'Cost': 3.14,
    'Is ColdChain': '',
}, {
    'Item Code': 'ABA003-TAB001-30',
    'Name': 'Test Item 3',
    'Category': '',
    'Sub Category': 'SUBCAT3',
    'Volume': '9999',
    'Weight': '',
    'Cost': '',
    'Is ColdChain': False,
}]


ORDER_DETAILS_EXAMPLE_DATA = [{
    'Customer Order Number': 'A0001',
    'Order Received Date (DD/MM/YYYY)': '04/01/2022',
    'Customer ID': 'Private Clinic',
    'Customer Name': 'CLIENTTest1',
    'Item Code': 'ABA001-TAB001-30',
    'Item Name': 'Test Item 1',
    'Quantity': 2,
}, {
    'Customer Order Number': 'A0001',
    'Order Received Date (DD/MM/YYYY)': '04/01/2022',
    'Customer ID': 'Private Clinic',
    'Customer Name': 'CLIENTTest1',
    'Item Code': 'ABA002-TAB001-30',
    'Item Name': 'Test Item 2',
    'Quantity': 1,
}, {
    'Customer Order Number': 'A0002',
    'Order Received Date (DD/MM/YYYY)': '05/30/2022',
    'Customer ID': 'Private Clinic',
    'Customer Name': 'CLIENTTest2',
    'Item Code': 'ABA001-TAB001-30',
    'Item Name': 'Test Item 1',
    'Quantity': 3,
}]


SUPPLIER_EXAMPLE_DATA = [{
    'Supplier ID': 'SUP1',
    'Name': 'SUPPLIER1',
    'Address 1': 'Add1',
    'Address 2': 'Add2',
    'Address 3': 'Add3',
    'City': 'City1',
    'State': 'State1',
    'Country': 'Country1',
    'Phone': '9123912',
    'Email': 'email@email.email',
    'LatitudeLongitude': 'latlong',
}, {
    'Supplier ID': 'SUP2',
    'Name': 'SUPPLIER2',
    'Address 1': '',
    'Address 2': '',
    'Address 3': '',
    'City': '',
    'State': '',
    'Country': '',
    'Phone': '',
    'Email': '',
    'LatitudeLongitude': '',
}]
